// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vessel/vessel.proto

/*
Package go_micro_srv_vessel is a generated protocol buffer package.

It is generated from these files:
	proto/vessel/vessel.proto

It has these top-level messages:
	Vessel
	Specification
	Response
*/
package go_micro_srv_vessel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vessel struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Capacity   int32  `protobuf:"varint,2,opt,name=capacity" json:"capacity,omitempty"`
	MaxWeight  int32  `protobuf:"varint,3,opt,name=max_weight,json=maxWeight" json:"max_weight,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Availiable bool   `protobuf:"varint,5,opt,name=availiable" json:"availiable,omitempty"`
	OwnerId    string `protobuf:"bytes,6,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
}

func (m *Vessel) Reset()                    { *m = Vessel{} }
func (m *Vessel) String() string            { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()               {}
func (*Vessel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailiable() bool {
	if m != nil {
		return m.Availiable
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Specification struct {
	Capacity  int32 `protobuf:"varint,1,opt,name=capacity" json:"capacity,omitempty"`
	MaxWeight int32 `protobuf:"varint,2,opt,name=max_weight,json=maxWeight" json:"max_weight,omitempty"`
}

func (m *Specification) Reset()                    { *m = Specification{} }
func (m *Specification) String() string            { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()               {}
func (*Specification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Vessel  *Vessel   `protobuf:"bytes,1,opt,name=vessel" json:"vessel,omitempty"`
	Vessels []*Vessel `protobuf:"bytes,2,rep,name=vessels" json:"vessels,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func init() {
	proto.RegisterType((*Vessel)(nil), "go.micro.srv.vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "go.micro.srv.vessel.Specification")
	proto.RegisterType((*Response)(nil), "go.micro.srv.vessel.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	FindAvailiable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) FindAvailiable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailiable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	FindAvailiable(context.Context, *Specification, *Response) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) FindAvailiable(ctx context.Context, in *Specification, out *Response) error {
	return h.VesselServiceHandler.FindAvailiable(ctx, in, out)
}

func init() { proto.RegisterFile("proto/vessel/vessel.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x75, 0x0b, 0x94, 0x32, 0x06, 0x0e, 0xeb, 0x65, 0xc1, 0x60, 0x9a, 0x9e, 0x7a, 0x5a, 0x13,
	0x88, 0x1f, 0xe0, 0xc5, 0x44, 0x8f, 0x25, 0xea, 0x91, 0x2c, 0xdb, 0x01, 0x27, 0x69, 0xbb, 0x4d,
	0xb7, 0x29, 0xf8, 0x3b, 0x7e, 0xa9, 0xc9, 0x16, 0x54, 0x4c, 0xa3, 0xa7, 0x9d, 0x79, 0xf3, 0xe6,
	0xe5, 0xcd, 0x5b, 0x98, 0x96, 0x95, 0xa9, 0xcd, 0x6d, 0x83, 0xd6, 0x62, 0x76, 0x7c, 0xa4, 0xc3,
	0xf8, 0xd5, 0xce, 0xc8, 0x9c, 0x74, 0x65, 0xa4, 0xad, 0x1a, 0xd9, 0x8e, 0xa2, 0x0f, 0x06, 0xfe,
	0x8b, 0x2b, 0xf9, 0x04, 0x3c, 0x4a, 0x05, 0x0b, 0x59, 0x3c, 0x4a, 0x3c, 0x4a, 0xf9, 0x0c, 0x02,
	0xad, 0x4a, 0xa5, 0xa9, 0x7e, 0x17, 0x5e, 0xc8, 0xe2, 0x41, 0xf2, 0xd5, 0xf3, 0x39, 0x40, 0xae,
	0x0e, 0xeb, 0x3d, 0xd2, 0xee, 0xad, 0x16, 0x3d, 0x37, 0x1d, 0xe5, 0xea, 0xf0, 0xea, 0x00, 0xce,
	0xa1, 0x5f, 0xa8, 0x1c, 0x45, 0xdf, 0x89, 0xb9, 0x9a, 0xdf, 0x00, 0xa8, 0x46, 0x51, 0x46, 0x6a,
	0x93, 0xa1, 0x18, 0x84, 0x2c, 0x0e, 0x92, 0x1f, 0x08, 0x9f, 0x42, 0x60, 0xf6, 0x05, 0x56, 0x6b,
	0x4a, 0x85, 0xef, 0xf6, 0x86, 0xae, 0x7f, 0x4c, 0xa3, 0x27, 0x18, 0xaf, 0x4a, 0xd4, 0xb4, 0x25,
	0xad, 0x6a, 0x32, 0xc5, 0x99, 0x35, 0xf6, 0xa7, 0x35, 0xef, 0x97, 0xb5, 0xa8, 0x81, 0x20, 0x41,
	0x5b, 0x9a, 0xc2, 0x22, 0x5f, 0x82, 0xdf, 0xc6, 0xe0, 0x44, 0x2e, 0x17, 0xd7, 0xb2, 0x23, 0x22,
	0xd9, 0xc6, 0x93, 0x1c, 0xa9, 0xfc, 0x0e, 0x86, 0x6d, 0x65, 0x85, 0x17, 0xf6, 0xfe, 0xdb, 0x3a,
	0x71, 0x17, 0x5b, 0x18, 0xb7, 0xd0, 0x0a, 0xab, 0x86, 0x34, 0xf2, 0x67, 0x98, 0x3c, 0x50, 0x91,
	0xde, 0x7f, 0x27, 0x10, 0x75, 0x0a, 0x9d, 0x5d, 0x3e, 0x9b, 0x77, 0x72, 0x4e, 0x17, 0x45, 0x17,
	0x1b, 0xdf, 0x7d, 0xf6, 0xf2, 0x33, 0x00, 0x00, 0xff, 0xff, 0x21, 0x8a, 0x0c, 0x67, 0x09, 0x02,
	0x00, 0x00,
}
